name: Main workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4
      - name: Build
        run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh  
